version: "3.9"

services:
    cli:
        build: .
        environment:
            - DATABASE_URL
            - LEXOFFICE_APIKEY
        depends_on:
            - db

    db:
        image: mongodb/mongodb-community-server
        ports:
          - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
        volumes:
          - data:/data/db

volumes:
  data: