/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContactAddresses {
    #[serde(rename = "billing", skip_serializing_if = "Option::is_none")]
    pub billing: Option<Vec<crate::models::Address>>,
    #[serde(rename = "shipping", skip_serializing_if = "Option::is_none")]
    pub shipping: Option<Vec<crate::models::Address>>,
}

impl ContactAddresses {
    pub fn new() -> ContactAddresses {
        ContactAddresses {
            billing: None,
            shipping: None,
        }
    }
}


