/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerOrVendorDetails {
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<f32>,
}

impl CustomerOrVendorDetails {
    pub fn new() -> CustomerOrVendorDetails {
        CustomerOrVendorDetails {
            number: None,
        }
    }
}


