/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Dunning {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "organizationId", skip_serializing_if = "Option::is_none")]
    pub organization_id: Option<uuid::Uuid>,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<String>,
    #[serde(rename = "updatedDate", skip_serializing_if = "Option::is_none")]
    pub updated_date: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<Language>,
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    #[serde(rename = "voucherStatus", skip_serializing_if = "Option::is_none")]
    pub voucher_status: Option<VoucherStatus>,
    #[serde(rename = "voucherNumber", skip_serializing_if = "Option::is_none")]
    pub voucher_number: Option<String>,
    #[serde(rename = "voucherDate", skip_serializing_if = "Option::is_none")]
    pub voucher_date: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<crate::models::VoucherAddress>>,
    #[serde(rename = "lineItems", skip_serializing_if = "Option::is_none")]
    pub line_items: Option<Vec<crate::models::LineItem>>,
    #[serde(rename = "taxConditions", skip_serializing_if = "Option::is_none")]
    pub tax_conditions: Option<Box<crate::models::TaxConditions>>,
    #[serde(rename = "shippingConditions", skip_serializing_if = "Option::is_none")]
    pub shipping_conditions: Option<Box<crate::models::ShippingConditions>>,
    #[serde(rename = "relatedVouchers", skip_serializing_if = "Option::is_none")]
    pub related_vouchers: Option<Vec<crate::models::RelatedVoucher>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "introduction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub introduction: Option<Option<String>>,
    #[serde(rename = "remark", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remark: Option<Option<String>>,
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<Box<crate::models::File>>,
}

impl Dunning {
    pub fn new() -> Dunning {
        Dunning {
            id: None,
            organization_id: None,
            created_date: None,
            updated_date: None,
            version: None,
            language: None,
            archived: None,
            voucher_status: None,
            voucher_number: None,
            voucher_date: None,
            address: None,
            line_items: None,
            tax_conditions: None,
            shipping_conditions: None,
            related_vouchers: None,
            title: None,
            introduction: None,
            remark: None,
            files: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Language {
    #[serde(rename = "de")]
    De,
    #[serde(rename = "en")]
    En,
}

impl Default for Language {
    fn default() -> Language {
        Self::De
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VoucherStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "paid")]
    Paid,
    #[serde(rename = "voided")]
    Voided,
}

impl Default for VoucherStatus {
    fn default() -> VoucherStatus {
        Self::Draft
    }
}

