/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentItem {
    #[serde(rename = "paymentItemType", skip_serializing_if = "Option::is_none")]
    pub payment_item_type: Option<PaymentItemType>,
    #[serde(rename = "postingDate", skip_serializing_if = "Option::is_none")]
    pub posting_date: Option<String>,
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Currency>,
}

impl PaymentItem {
    pub fn new() -> PaymentItem {
        PaymentItem {
            payment_item_type: None,
            posting_date: None,
            amount: None,
            currency: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentItemType {
    #[serde(rename = "partPaymentFinancialTransaction")]
    PartPaymentFinancialTransaction,
    #[serde(rename = "partPaymentCreditNote")]
    PartPaymentCreditNote,
    #[serde(rename = "partPaymentCashBox")]
    PartPaymentCashBox,
    #[serde(rename = "manualPayment")]
    ManualPayment,
    #[serde(rename = "cashDiscount")]
    CashDiscount,
    #[serde(rename = "dunningCosts")]
    DunningCosts,
    #[serde(rename = "currencyConversion")]
    CurrencyConversion,
}

impl Default for PaymentItemType {
    fn default() -> PaymentItemType {
        Self::PartPaymentFinancialTransaction
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "EUR")]
    Eur,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::Eur
    }
}

