/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RolesDetails {
    #[serde(rename = "customer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer: Option<Option<Box<crate::models::CustomerOrVendorDetails>>>,
    #[serde(rename = "vendor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vendor: Option<Option<Box<crate::models::CustomerOrVendorDetails>>>,
}

impl RolesDetails {
    pub fn new() -> RolesDetails {
        RolesDetails {
            customer: None,
            vendor: None,
        }
    }
}


