/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortProperties {
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<String>,
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<String>,
    #[serde(rename = "ignoreCase", skip_serializing_if = "Option::is_none")]
    pub ignore_case: Option<bool>,
    #[serde(rename = "nullHandling", skip_serializing_if = "Option::is_none")]
    pub null_handling: Option<String>,
    #[serde(rename = "ascending", skip_serializing_if = "Option::is_none")]
    pub ascending: Option<bool>,
}

impl SortProperties {
    pub fn new() -> SortProperties {
        SortProperties {
            direction: None,
            property: None,
            ignore_case: None,
            null_handling: None,
            ascending: None,
        }
    }
}


