/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaxAmount {
    #[serde(rename = "taxRatePercentage")]
    pub tax_rate_percentage: f32,
    #[serde(rename = "taxAmount")]
    pub tax_amount: f32,
    #[serde(rename = "netAmount")]
    pub net_amount: f32,
}

impl TaxAmount {
    pub fn new(tax_rate_percentage: f32, tax_amount: f32, net_amount: f32) -> TaxAmount {
        TaxAmount {
            tax_rate_percentage,
            tax_amount,
            net_amount,
        }
    }
}


