/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VoucherAddress : Address for CreditNote/DeliveryNote/Invoice



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoucherAddress {
    #[serde(rename = "contactId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "supplement", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplement: Option<Option<String>>,
    #[serde(rename = "street", skip_serializing_if = "Option::is_none")]
    pub street: Option<String>,
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(rename = "zip", skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(rename = "contactPerson", skip_serializing_if = "Option::is_none")]
    pub contact_person: Option<String>,
}

impl VoucherAddress {
    /// Address for CreditNote/DeliveryNote/Invoice
    pub fn new() -> VoucherAddress {
        VoucherAddress {
            contact_id: None,
            name: None,
            supplement: None,
            street: None,
            city: None,
            zip: None,
            country_code: None,
            contact_person: None,
        }
    }
}


