[package]
name = "lexoffice-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openapi = { path = "./openapi" }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
diesel = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15"
uuid = { version = "^1.0", features = ["serde", "v4"] }
once_cell = "1.19.0"