/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RelatedVoucher {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "voucherNumber", skip_serializing_if = "Option::is_none")]
    pub voucher_number: Option<String>,
    #[serde(rename = "voucherType", skip_serializing_if = "Option::is_none")]
    pub voucher_type: Option<String>,
}

impl RelatedVoucher {
    pub fn new() -> RelatedVoucher {
        RelatedVoucher {
            id: None,
            voucher_number: None,
            voucher_type: None,
        }
    }
}


