/*
 * lexoffice Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaxAmount {
    #[serde(rename = "taxRatePercentage", skip_serializing_if = "Option::is_none")]
    pub tax_rate_percentage: Option<f32>,
    #[serde(rename = "taxAmount", skip_serializing_if = "Option::is_none")]
    pub tax_amount: Option<f32>,
    #[serde(rename = "netAmount", skip_serializing_if = "Option::is_none")]
    pub net_amount: Option<f32>,
}

impl TaxAmount {
    pub fn new() -> TaxAmount {
        TaxAmount {
            tax_rate_percentage: None,
            tax_amount: None,
            net_amount: None,
        }
    }
}


